name: Shriyak's Website
description: Personal website of Shriyak Sridhar
paginate: 10
baseurl: ''

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Build settings
markdown: kramdown
permalink: pretty

social:
  - title: twitter
    url: https://twitter.com
  - title: github
    url: https://github.com/ShriyakSridhar
  - title: linkedin
    url:
