name: Shriyak's Website
description: Personal website of Shriyak Sridhar
paginate: 10
baseurl: ''

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

social:
  - name: Twitter
    icon: twitter
    username: TheBenCentra
    url: https://twitter.com/TheBenCentra
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username: thebencentra
    url:
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: bencentra
    url: https://github.com/bencentra
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Ben Centra
    url: https://www.linkedin.com/pub/ben-centra/47/769/60a
    desc: Connect with me on LinkedIn
    share: true

  - name: Instagram
    icon: instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false


